aminoAcids = [
    "ASN",
    "LEU",
    "GLU",
    "PHE",
    "LYS",
    "TYR",
    "GLN",
    "THR",
    "CYS",
    "SER",
    "MET",
    "ALA",
    "ILE",
    "PRO",
    "ARG",
    "GLY",
    "DSN",
    "ASP",
    "VAL",
    "TRP",
    "DCY",
    "HIS",
    "SHC",
    "0AZ",
    "MCS",
    "07O",
    "6CW",
    "BCX",
    "OHS",
    "HTR",
    "0A9",
    "CR5",
    "4CF",
    "SET",
    "MYN",
    "DBZ",
    "SLZ",
    "NPI",
    "AEI",
    "API",
    "XPR",
    "AYA",
    "ASQ",
    "NYS",
    "CS4",
    "TYT",
    "B3K",
    "4AF",
    "B3A",
    "HIP",
    "MGY",
    "LE1",
    "CS1",
    "4FB",
    "DNS",
    "SNC",
    "ORQ",
    "MT2",
    "MCL",
    "CS3",
    "NNH",
    "ASA",
    "DHN",
    "5PG",
    "HZP",
    "CYW",
    "OMT",
    "Z70",
    "SVV",
    "PG1",
    "GHG",
    "FC0",
    "JJL",
    "CYQ",
    "TY1",
    "TQI",
    "DBY",
    "BG1",
    "HIC",
    "0A0",
    "2VA",
    "DAB",
    "GPL",
    "AGQ",
    "1PA",
    "HPC",
    "M30",
    "LPS",
    "DYS",
    "LEN",
    "1TQ",
    "ALN",
    "B2V",
    "DAH",
    "ESB",
    "SCY",
    "SVY",
    "HV5",
    "ZZD",
    "OMY",
    "DON",
    "CMH",
    "ZCL",
    "ALM",
    "SVX",
    "B2F",
    "CIR",
    "HS9",
    "0A2",
    "OHI",
    "FP9",
    "B2A",
    "ORN",
    "LLP",
    "2MT",
    "CLE",
    "OMX",
    "MAI",
    "HS8",
    "BLE",
    "LMQ",
    "VR0",
    "LYX",
    "HPE",
    "PCA",
    "CYM",
    "JJJ",
    "FT6",
    "CME",
    "NTY",
    "ALC",
    "CYG",
    "BTK",
    "TQQ",
    "CYF",
    "S2P",
    "RCY",
    "SEG",
    "FTY",
    "CS0",
    "FTR",
    "GLJ",
    "IT1",
    "ARM",
    "THC",
    "LWY",
    "MC1",
    "9DS",
    "HBN",
    "TH5",
    "TY8",
    "BB6",
    "LPG",
    "PRV",
    "ME0",
    "9DN",
    "CAS",
    "CZZ",
    "2RA",
    "FZN",
    "VAF",
    "TY9",
    "AN8",
    "DLS",
    "P3Q",
    "PTM",
    "ILG",
    "MHO",
    "AIB",
    "NC1",
    "KNB",
    "CSZ",
    "CSP",
    "SMF",
    "CSW",
    "LLO",
    "AGM",
    "SEE",
    "RE3",
    "LP6",
    "ABA",
    "03Y",
    "3CF",
    "JJK",
    "5CS",
    "LLZ",
    "PHD",
    "HHI",
    "AR4",
    "NZH",
    "P1L",
    "C6C",
    "HAC",
    "AR2",
    "CMT",
    "CGU",
    "3QN",
    "MHU",
    "AHP",
    "CY0",
    "CY3",
    "TYJ",
    "FME",
    "MHS",
    "CZ2",
    "PRK",
    "BIU",
    "5HP",
    "Z3E",
    "OTH",
    "TTQ",
    "MEN",
    "CY1",
    "M3R",
    "PM3",
    "R1A",
    "AZK",
    "4IN",
    "ECC",
    "NIY",
    "TCR",
    "R7A",
    "0BN",
    "FGP",
    "I2M",
    "THZ",
    "BIF",
    "MNV",
    "LVG",
    "26B",
    "02K",
    "LMF",
    "0NC",
    "LYN",
    "PYA",
    "TTS",
    "CGA",
    "CSJ",
    "GLZ",
    "BB7",
    "MGG",
    "UM2",
    "EXY",
    "MLU",
    "TAV",
    "NLQ",
    "IAM",
    "MSL",
    "CYA",
    "NLP",
    "PAT",
    "MGN",
    "GSC",
    "2AG",
    "DNP",
    "IAR",
    "3MY",
    "NMC",
    "PAS",
    "ONH",
    "TRX",
    "CAF",
    "PVH",
    "4U7",
    "PHM",
    "TRQ",
    "PHL",
    "LCK",
    "SYS",
    "CEA",
    "MME",
    "B1F",
    "2LU",
    "FLE",
    "0AB",
    "NCB",
    "0AC",
    "LYU",
    "MLY",
    "9NV",
    "FVA",
    "HAR",
    "KCX",
    "MK8",
    "PR7",
    "LA2",
    "LAA",
    "ZYJ",
    "ZYK",
    "CHP",
    "TOX",
    "SEL",
    "MBQ",
    "GME",
    "FLA",
    "AA4",
    "LYR",
    "GLQ",
    "9NF",
    "BFD",
    "ASI",
    "1TY",
    "6CL",
    "PHA",
    "3MD",
    "DHA",
    "OCS",
    "MNL",
    "P2Q",
    "HSO",
    "3XH",
    "FB5",
    "HOX",
    "DPL",
    "HMR",
    "NLO",
    "DBU",
    "0A8",
    "N10",
    "BCS",
    "C4R",
    "AFA",
    "C5C",
    "HRG",
    "3GA",
    "DBS",
    "SEP",
    "EFC",
    "HPQ",
    "T0I",
    "3GL",
    "MHL",
    "NBQ",
    "BTA",
    "AKL",
    "CTH",
    "MYK",
    "I58",
    "BLY",
    "NYB",
    "TRO",
    "PE1",
    "NLE",
    "TRN",
    "T11",
    "SHP",
    "HSE",
    "Z01",
    "ALS",
    "A5N",
    "TPO",
    "BUG",
    "TIH",
    "HYP",
    "APK",
    "QDS",
    "TYQ",
    "KGC",
    "LEF",
    "UDS",
    "BBC",
    "AZH",
    "MVA",
    "KOR",
    "2ML",
    "BTC",
    "SNN",
    "B3D",
    "B27",
    "B3E",
    "GHW",
    "CYR",
    "TY5",
    "LEH",
    "TIS",
    "ASB",
    "DMK",
    "DMH",
    "23F",
    "IML",
    "OCY",
    "B2I",
    "HRP",
    "OTY",
    "GHC",
    "MAA",
    "TY2",
    "YCM",
    "TY3",
    "MEG",
    "FOE",
    "ALY",
    "CXM",
    "ML3",
    "5AB",
    "ZU0",
    "DC2",
    "SVA",
    "3O3",
    "B3U",
    "2MR",
    "AGT",
    "ICY",
    "MLE",
    "SCS",
    "2P0",
    "2TY",
    "SVW",
    "KPI",
    "DPP",
    "5OH",
    "DIR",
    "ZZJ",
    "F2F",
    "PTR",
    "CML",
    "B3Y",
    "UF0",
    "POM",
    "SIB",
    "RGL",
    "4DP",
    "SAH",
    "HIQ",
    "OAS",
    "IYR",
    "BB9",
    "TYY",
    "HIA",
    "CLG",
    "0AR",
    "TH6",
    "PYX",
    "7JA",
    "SBL",
    "AZY",
    "LGY",
    "AA3",
    "200",
    "AZS",
    "FCL",
    "NFA",
    "0FL",
    "AAR",
    "VAD",
    "BPE",
    "CSB",
    "STY",
    "CSA",
    "K1R",
    "SLL",
    "HL2",
    "LYZ",
    "ALO",
    "C1X",
    "ELY",
    "DPQ",
    "DOH",
    "CSX",
    "OSE",
    "RE0",
    "6HN",
    "2XA",
    "08P",
    "CSR",
    "SME",
    "PRS",
    "CCS",
    "HQA",
    "4CY",
    "SOC",
    "BSE",
    "CSS",
    "S2C",
    "ECX",
    "4FW",
    "LBY",
    "SOY",
    "LYF",
    "NA8",
    "H5M",
    "PCC",
    "PSW",
    "PR4",
    "CYD",
    "BOR",
    "SCH",
    "TBG",
    "PTH",
    "VAH",
    "IZO",
    "MEU",
    "HT7",
    "M0H",
    "B3X",
    "ASL",
    "LEM",
    "TCQ",
    "CSU",
    "4PH",
    "1PI",
    "SMC",
    "TS9",
    "LCX",
    "QIL",
    "LPD",
    "LLY",
    "XX1",
    "PCS",
    "LVN",
    "ILX",
    "PRJ",
    "TNB",
    "FHO",
    "NPH",
    "3NF",
    "3PX",
    "AN6",
    "TNR",
    "GT9",
    "PBF",
    "PGY",
    "N7P",
    "LME",
    "FFM",
    "XCN",
    "0A1",
    "MLL",
    "CSE",
    "M2L",
    "C1T",
    "CSD",
    "R1B",
    "CY4",
    "2FM",
    "TYI",
    "UM1",
    "TYO",
    "HR7",
    "SXE",
    "CWR",
    "PBB",
    "GAU",
    "MEA",
    "L3O",
    "AHB",
    "TYN",
    "VB1",
    "LYM",
    "TMD",
    "LED",
    "QMM",
    "AHO",
    "9NR",
    "MH1",
    "R4K",
    "IGL",
    "IIL",
    "HVA",
    "CSO",
    "BNN",
    "TLY",
    "R1F",
    "BH2",
    "MEQ",
    "C3Y",
    "PAQ",
    "NMM",
    "SEM",
    "QPH",
    "LTR",
    "SEC",
    "X2W",
    "SEB",
    "SAC",
    "G01",
    "MLZ",
    "0AK",
    "0AH",
    "MA",
    "SUN",
    "SHR",
    "GLH",
    "SGB",
    "BB8",
    "MMO",
    "PSA",
    "IEL",
    "FGL",
    "PR9",
    "HY3",
    "MIS",
    "SEN",
    "PHI",
    "TMB",
    "A9D",
    "TYS",
    "TNY",
    "DNL",
    "NVA",
    "CTE",
    "0CS",
    "TBM",
    "XSN",
    "MP8",
    "MIR",
    "M3L",
    "TRG",
    "MSO",
    "HTI",
    "TYB",
    "KBE",
    "1AC",
    "PPN",
    "SAR",
    "MPQ",
    "NEM",
    "PEC",
    "MSE",
    "DM0",
    "NEP",
    "OMH",
    "2CO",
    "TRW",
    "GMA",
    "PSH",
    "SDP",
    "M2S",
    "CLH",
    "DDZ",
    "MH6",
    "KYQ",
    "CWD",
    "NLN",
    "NOT",
    "BMT",
    "ASK",
    "PFF",
    "V1A",
    "BHD",
    "TPL",
    "NWD",
    "2HF",
    "PR3",
    "BUC",
    "OXX",
    "NAL",
    "UMA",
    "3AH",
    "HNC",
    "LAL",
    "NAM",
    "DDE",
    "4HT",
    "0AF",
    "0AG",
    "HLU",
    "PF5",
    "P2Y",
    "WFP",
    "GSU",
    "OLZ",
    "TPQ",
    "0AA",
    "TEF",
    "FB6",
    "ACL",
    "9NE",
    "LDH",
    "KST",
    "TFQ",
    "HSL",
]


standardAminoAcids = [
    "GLY",
    "PRO",
    "ALA",
    "VAL",
    "LEU",
    "ILE",
    "MET",
    "CYS",
    "PHE",
    "TYR",
    "TRP",
    "HIS",
    "LYS",
    "ARG",
    "GLN",
    "ASN",
    "GLU",
    "SER",
    "THR",
    "ASP",
    "SEC",
    "PYL",
    "ASX",
    "GLX",
    "XAA",
]


nonStandardAminoAcids = {
    "02K": "ALA",
    "03Y": "CYS",
    "07O": "CYS",
    "08P": "DCY",
    "0A0": "ASP",
    "0A1": "TYR",
    "0A2": "LYS",
    "0A8": "CYS",
    "0A9": "PHE",
    "0AA": "VAL",
    "0AB": "VAL",
    "0AC": "GLY",
    "0AF": "TRP",
    "0AG": "LEU",
    "0AH": "SER",
    "0AK": "ASP",
    "0AR": "ARG",
    "0AZ": "PRO",
    "0BN": "PHE",
    "0CS": "ALA",
    "0FL": "ALA",
    "0NC": "ALA",
    "1AC": "ALA",
    "1PA": "PHE",
    "1PI": "ALA",
    "1TQ": "TRP",
    "1TY": "TYR",
    "200": "PHE",
    "2ML": "LEU",
    "23F": "PHE",
    "26B": "THR",
    "2AG": "ALA",
    "2CO": "CYS",
    "2FM": "MET",
    "2HF": "HIS",
    "2LU": "LEU",
    "2MR": "ARG",
    "2MT": "PRO",
    "2P0": "PRO",
    "2RA": "ALA",
    "2TY": "TYR",
    "2VA": "VAL",
    "2XA": "CYS",
    "3AH": "HIS",
    "3CF": "PHE",
    "3GA": "ALA",
    "3GL": "GLU",
    "3MD": "ASP",
    "3MY": "TYR",
    "3NF": "TYR",
    "3O3": "GLU",
    "3PX": "PRO",
    "3QN": "LYS",
    "3XH": "GLY",
    "4AF": "PHE",
    "4CF": "PHE",
    "4CY": "MET",
    "4DP": "TRP",
    "4FB": "PRO",
    "4FW": "TRP",
    "4HT": "TRP",
    "4IN": "TRP",
    "4PH": "PHE",
    "4U7": "ALA",
    "5AB": "ALA",
    "5CS": "CYS",
    "5HP": "GLU",
    "5OH": "ALA",
    "5PG": "GLY",
    "6CL": "LYS",
    "6CW": "TRP",
    "6HN": "LYS",
    "7JA": "ILE",
    "9DN": "ASN",
    "9DS": "GLY",
    "9NE": "GLU",
    "9NF": "PHE",
    "9NR": "ARG",
    "9NV": "VAL",
    "A5N": "ASN",
    "A9D": "SER",
    "AA3": "ALA",
    "AA4": "ALA",
    "AAR": "ARG",
    "ABA": "ALA",
    "ACL": "ARG",
    "AEI": "ASP",
    "AFA": "ASN",
    "AGM": "ARG",
    "AGQ": "TYR",
    "AGT": "CYS",
    "AHB": "ASN",
    "AHO": "ALA",
    "AHP": "ALA",
    "AIB": "ALA",
    "AKL": "ASP",
    "ALC": "ALA",
    "ALM": "ALA",
    "ALN": "ALA",
    "ALO": "THR",
    "ALS": "ALA",
    "ALY": "LYS",
    "ASQ": "ASP",
    "AN6": "LEU",
    "AN8": "ALA",
    "API": "LYS",
    "APK": "LYS",
    "AR2": "ARG",
    "AR4": "GLU",
    "ARM": "ARG",
    "ASA": "ASP",
    "ASB": "ASP",
    "ASI": "ASP",
    "ASK": "ASP",
    "ASL": "ASP",
    "AYA": "ALA",
    "AZH": "ALA",
    "AZK": "LYS",
    "AZS": "SER",
    "AZY": "TYR",
    "B1F": "PHE",
    "B27": "THR",
    "B2A": "ALA",
    "B2F": "PHE",
    "B2I": "ILE",
    "B2V": "VAL",
    "B3A": "ALA",
    "B3D": "ASP",
    "B3E": "GLU",
    "B3K": "LYS",
    "B3U": "HIS",
    "B3X": "ASN",
    "B3Y": "TYR",
    "BFD": "ASP",
    "BB6": "CYS",
    "BB7": "CYS",
    "BB8": "PHE",
    "BB9": "CYS",
    "BBC": "CYS",
    "BCS": "CYS",
    "BCX": "CYS",
    "BG1": "SER",
    "BH2": "ASP",
    "BHD": "ASP",
    "BIF": "PHE",
    "BIU": "ILE",
    "BLE": "LEU",
    "BLY": "LYS",
    "BMT": "THR",
    "BNN": "PHE",
    "BOR": "ARG",
    "BPE": "CYS",
    "BSE": "SER",
    "BTA": "LEU",
    "BTC": "CYS",
    "BTK": "LYS",
    "BUC": "CYS",
    "BUG": "VAL",
    "C1T": "CYS",
    "C1X": "LYS",
    "C3Y": "CYS",
    "C4R": "CYS",
    "C5C": "CYS",
    "C6C": "CYS",
    "CAF": "CYS",
    "CAS": "CYS",
    "CCS": "CYS",
    "CEA": "CYS",
    "CGA": "GLU",
    "CGU": "GLU",
    "CHP": "GLY",
    "CIR": "ARG",
    "CLE": "LEU",
    "CLG": "LYS",
    "CLH": "LYS",
    "CME": "CYS",
    "CMH": "CYS",
    "CML": "CYS",
    "CMT": "CYS",
    "CYM": "CYS",
    "CR5": "GLY",
    "CS0": "CYS",
    "CS1": "CYS",
    "CS3": "CYS",
    "CS4": "CYS",
    "CSA": "CYS",
    "CSB": "CYS",
    "CSD": "CYS",
    "CSE": "CYS",
    "CSJ": "CYS",
    "CSO": "CYS",
    "CSP": "CYS",
    "CSR": "CYS",
    "CSS": "CYS",
    "CSU": "CYS",
    "CSW": "CYS",
    "CSX": "CYS",
    "CSZ": "CYS",
    "CTE": "TRP",
    "CTH": "THR",
    "CWD": "ALA",
    "CWR": "SER",
    "CXM": "MET",
    "CY0": "CYS",
    "CY1": "CYS",
    "CY3": "CYS",
    "CY4": "CYS",
    "CYA": "CYS",
    "CYD": "CYS",
    "CYF": "CYS",
    "CYG": "CYS",
    "CYQ": "CYS",
    "CYR": "CYS",
    "CYW": "CYS",
    "CZ2": "CYS",
    "CZZ": "CYS",
    "DAB": "ALA",
    "DAH": "PHE",
    "DBS": "SER",
    "DBU": "THR",
    "DBY": "TYR",
    "DBZ": "ALA",
    "DC2": "CYS",
    "DDE": "HIS",
    "DDZ": "ALA",
    "DHA": "SER",
    "DHN": "VAL",
    "DIR": "ARG",
    "DLS": "LYS",
    "DM0": "LYS",
    "DMH": "ASN",
    "DMK": "ASP",
    "DNL": "LYS",
    "DNP": "ALA",
    "DNS": "LYS",
    "DOH": "ASP",
    "DON": "LEU",
    "DPL": "PRO",
    "DPP": "ALA",
    "DPQ": "TYR",
    "DYS": "CYS",
    "ECC": "GLN",
    "ECX": "CYS",
    "EFC": "CYS",
    "ELY": "LYS",
    "ESB": "TYR",
    "EXY": "LEU",
    "F2F": "PHE",
    "FB5": "ALA",
    "FB6": "ALA",
    "FC0": "PHE",
    "FCL": "PHE",
    "FFM": "CYS",
    "FGL": "GLY",
    "FGP": "SER",
    "FHO": "LYS",
    "FLA": "ALA",
    "FLE": "LEU",
    "FME": "MET",
    "FOE": "CYS",
    "FP9": "PRO",
    "FT6": "TRP",
    "FTR": "TRP",
    "FTY": "TYR",
    "FVA": "VAL",
    "FZN": "LYS",
    "G01": "GLU",
    "GAU": "GLU",
    "GHC": "GLU",
    "GHG": "GLN",
    "GHW": "GLU",
    "GLH": "GLN",
    "GLJ": "GLU",
    "GLQ": "GLU",
    "GLZ": "GLY",
    "GMA": "GLU",
    "GME": "GLU",
    "GPL": "LYS",
    "GSC": "GLY",
    "GSU": "GLU",
    "GT9": "CYS",
    "H5M": "PRO",
    "HAC": "ALA",
    "HAR": "ARG",
    "HBN": "HIS",
    "PCA": "GLU",
    "HHI": "HIS",
    "HIA": "HIS",
    "HIC": "HIS",
    "HIP": "HIS",
    "HIQ": "HIS",
    "HRP": "TRP",
    "HL2": "LEU",
    "HLU": "LEU",
    "HMR": "ARG",
    "HNC": "CYS",
    "HOX": "PHE",
    "HPC": "PHE",
    "HPE": "PHE",
    "HPQ": "PHE",
    "HQA": "ALA",
    "HR7": "ARG",
    "HRG": "ARG",
    "HS8": "HIS",
    "HS9": "HIS",
    "HSE": "SER",
    "HSL": "SER",
    "HSO": "HIS",
    "HT7": "TRP",
    "HTI": "CYS",
    "HTR": "TRP",
    "HV5": "ALA",
    "HVA": "VAL",
    "HY3": "PRO",
    "HYP": "PRO",
    "HZP": "PRO",
    "I2M": "ILE",
    "I58": "LYS",
    "IAM": "ALA",
    "IAR": "ARG",
    "ICY": "CYS",
    "IEL": "LYS",
    "IGL": "GLY",
    "IIL": "ILE",
    "ILG": "GLU",
    "ILX": "ILE",
    "IML": "ILE",
    "IT1": "LYS",
    "IYR": "TYR",
    "IZO": "MET",
    "JJJ": "CYS",
    "JJK": "CYS",
    "JJL": "CYS",
    "K1R": "CYS",
    "KBE": "LYS",
    "KCX": "LYS",
    "KGC": "LYS",
    "LLO": "LYS",
    "KNB": "ALA",
    "KOR": "MET",
    "KPI": "LYS",
    "LYZ": "LYS",
    "KST": "LYS",
    "KYQ": "LYS",
    "L3O": "LEU",
    "LA2": "LYS",
    "LAA": "ASP",
    "LAL": "ALA",
    "LBY": "LYS",
    "LCK": "LYS",
    "LCX": "LYS",
    "LDH": "LYS",
    "LE1": "VAL",
    "LED": "LEU",
    "LEF": "LEU",
    "LEH": "LEU",
    "LEM": "LEU",
    "LEN": "LEU",
    "LGY": "LYS",
    "LLP": "LYS",
    "LLY": "LYS",
    "LLZ": "LYS",
    "LME": "GLU",
    "LMF": "LYS",
    "LMQ": "GLN",
    "LP6": "LYS",
    "LPD": "PRO",
    "LPG": "GLY",
    "LPS": "SER",
    "LTR": "TRP",
    "LVG": "GLY",
    "LVN": "VAL",
    "LWY": "PRO",
    "LYF": "LYS",
    "LYM": "LYS",
    "LYN": "LYS",
    "LYR": "LYS",
    "LYU": "LYS",
    "LYX": "LYS",
    "M0H": "CYS",
    "M2L": "LYS",
    "M2S": "MET",
    "M30": "GLY",
    "M3L": "LYS",
    "M3R": "LYS",
    "MA": "ALA",
    "MAA": "ALA",
    "MAI": "ARG",
    "MBQ": "TYR",
    "MC1": "SER",
    "MCL": "LYS",
    "MCS": "CYS",
    "ME0": "MET",
    "MEA": "PHE",
    "MEG": "GLU",
    "MEN": "ASN",
    "MEQ": "GLN",
    "MEU": "GLY",
    "MGG": "ARG",
    "MGN": "GLN",
    "MGY": "GLY",
    "MH1": "HIS",
    "MH6": "SER",
    "MHL": "LEU",
    "MHO": "MET",
    "MHS": "HIS",
    "MHU": "PHE",
    "MIR": "SER",
    "MIS": "SER",
    "MK8": "LEU",
    "ML3": "LYS",
    "MLE": "LEU",
    "MLL": "LEU",
    "MLU": "LEU",
    "MLY": "LYS",
    "MLZ": "LYS",
    "MME": "MET",
    "MMO": "ARG",
    "MNL": "LEU",
    "MNV": "VAL",
    "MP8": "PRO",
    "MPQ": "GLY",
    "MSE": "MET",
    "MSL": "MET",
    "MSO": "MET",
    "MT2": "MET",
    "MVA": "VAL",
    "MYK": "LYS",
    "MYN": "ARG",
    "N10": "SER",
    "NLN": "LEU",
    "N7P": "PRO",
    "NA8": "ALA",
    "NAL": "ALA",
    "NAM": "ALA",
    "NBQ": "TYR",
    "NC1": "SER",
    "NCB": "ALA",
    "NEM": "HIS",
    "NEP": "HIS",
    "NFA": "PHE",
    "NLO": "LEU",
    "NLP": "LEU",
    "NIY": "TYR",
    "NLE": "LEU",
    "NLQ": "GLN",
    "NMC": "GLY",
    "NMM": "ARG",
    "NNH": "ARG",
    "NOT": "LEU",
    "NPH": "CYS",
    "NPI": "ALA",
    "NTY": "TYR",
    "NVA": "VAL",
    "NWD": "ALA",
    "NYB": "CYS",
    "NYS": "CYS",
    "NZH": "HIS",
    "OAS": "SER",
    "OCS": "CYS",
    "OCY": "CYS",
    "OHI": "HIS",
    "OHS": "ASP",
    "OLZ": "SER",
    "OMH": "SER",
    "OMT": "MET",
    "OMX": "TYR",
    "OMY": "TYR",
    "ONH": "ALA",
    "ORN": "ALA",
    "ORQ": "ARG",
    "OSE": "SER",
    "OTH": "THR",
    "OTY": "TYR",
    "OXX": "ASP",
    "P1L": "CYS",
    "P2Q": "TYR",
    "P2Y": "PRO",
    "P3Q": "TYR",
    "PAQ": "TYR",
    "PAS": "ASP",
    "PAT": "TRP",
    "PBB": "CYS",
    "PBF": "PHE",
    "PCC": "PRO",
    "PCS": "PHE",
    "PE1": "LYS",
    "PEC": "CYS",
    "PF5": "PHE",
    "PFF": "PHE",
    "PG1": "SER",
    "PGY": "GLY",
    "PHA": "PHE",
    "PHD": "ASP",
    "PHI": "PHE",
    "PHL": "PHE",
    "PHM": "PHE",
    "PM3": "PHE",
    "POM": "PRO",
    "PPN": "PHE",
    "PR3": "CYS",
    "PR4": "PRO",
    "PR7": "PRO",
    "PR9": "PRO",
    "PRJ": "PRO",
    "PRK": "LYS",
    "PRS": "PRO",
    "PRV": "GLY",
    "PSA": "PHE",
    "PSH": "HIS",
    "PSW": "CYS",
    "PTH": "TYR",
    "PTM": "TYR",
    "PTR": "TYR",
    "PYA": "ALA",
    "PVH": "HIS",
    "PYX": "CYS",
    "QDS": "DSN",
    "QIL": "ILE",
    "QMM": "GLN",
    "QPH": "PHE",
    "R1A": "CYS",
    "R1B": "CYS",
    "R1F": "CYS",
    "R4K": "TRP",
    "R7A": "CYS",
    "RCY": "CYS",
    "RE0": "TRP",
    "RE3": "TRP",
    "RGL": "ARG",
    "S2C": "CYS",
    "S2P": "ALA",
    "SAC": "SER",
    "SAH": "CYS",
    "SAR": "GLY",
    "SBL": "SER",
    "SCH": "CYS",
    "SCS": "CYS",
    "SCY": "CYS",
    "SDP": "SER",
    "SEB": "SER",
    "SEC": "ALA",
    "SEE": "SER",
    "SEG": "ALA",
    "SEL": "SER",
    "SEM": "SER",
    "SEN": "SER",
    "SEP": "SER",
    "SET": "SER",
    "SGB": "SER",
    "SHC": "CYS",
    "SHP": "GLY",
    "SHR": "LYS",
    "SIB": "CYS",
    "SLL": "LYS",
    "SLZ": "LYS",
    "SMC": "CYS",
    "SME": "MET",
    "SMF": "PHE",
    "SNC": "CYS",
    "SNN": "ASN",
    "SOC": "CYS",
    "SOY": "SER",
    "STY": "TYR",
    "SUN": "SER",
    "SVA": "SER",
    "SVV": "SER",
    "SVW": "SER",
    "SVX": "SER",
    "SVY": "SER",
    "SXE": "SER",
    "SYS": "CYS",
    "T0I": "TYR",
    "T11": "PHE",
    "TAV": "ASP",
    "TBG": "VAL",
    "TBM": "THR",
    "TCQ": "TYR",
    "TCR": "TRP",
    "TEF": "PHE",
    "TFQ": "PHE",
    "TH5": "THR",
    "TH6": "THR",
    "THC": "THR",
    "THZ": "ARG",
    "TIH": "ALA",
    "TIS": "SER",
    "TLY": "LYS",
    "TMB": "THR",
    "TMD": "THR",
    "TNB": "CYS",
    "TNR": "SER",
    "TNY": "THR",
    "TOX": "TRP",
    "TPL": "TRP",
    "TPO": "THR",
    "TPQ": "TYR",
    "TQI": "TRP",
    "TQQ": "TRP",
    "TRG": "LYS",
    "TRN": "TRP",
    "TRO": "TRP",
    "TRQ": "TRP",
    "TRW": "TRP",
    "TRX": "TRP",
    "TS9": "ILE",
    "TTQ": "TRP",
    "TTS": "TYR",
    "TY1": "TYR",
    "TY2": "TYR",
    "TY3": "TYR",
    "TY5": "TYR",
    "TY8": "TYR",
    "TY9": "TYR",
    "TYB": "TYR",
    "TYI": "TYR",
    "TYJ": "TYR",
    "TYN": "TYR",
    "TYO": "TYR",
    "TYQ": "TYR",
    "TYS": "TYR",
    "TYT": "TYR",
    "TYY": "TYR",
    "UDS": "DSN",
    "UF0": "SER",
    "UM1": "ALA",
    "UM2": "ALA",
    "UMA": "ALA",
    "V1A": "CYS",
    "VAD": "VAL",
    "VAF": "VAL",
    "VAH": "VAL",
    "VB1": "LYS",
    "VR0": "ARG",
    "WFP": "PHE",
    "X2W": "GLU",
    "XCN": "CYS",
    "XPR": "PRO",
    "XSN": "ASN",
    "XX1": "LYS",
    "YCM": "CYS",
    "Z01": "ALA",
    "Z3E": "THR",
    "Z70": "HIS",
    "ZCL": "PHE",
    "ZU0": "THR",
    "ZYJ": "PRO",
    "ZYK": "PRO",
    "ZZD": "CYS",
    "ZZJ": "ALA",
}


nucleicAcids = [
    "T",
    "C",
    "DC",
    "DI",
    "DU",
    "DG",
    "A",
    "DA",
    "G",
    "U",
    "DT",
    "C2S",
    "US5",
    "DRT",
    "DNR",
    "2BT",
    "US2",
    "OHU",
    "UCL",
    "LGP",
    "2BD",
    "UMP",
    "TPC",
    "IG",
    "2BU",
    "4SU",
    "A47",
    "MRG",
    "T6A",
    "RIA",
    "47C",
    "NDN",
    "OMU",
    "A6C",
    "2DT",
    "TPG",
    "XCY",
    "AP7",
    "PDU",
    "OMC",
    "TTM",
    "A40",
    "A6U",
    "G7M",
    "IMC",
    "6HA",
    "5CG",
    "FOX",
    "T5S",
    "T41",
    "BVP",
    "6HC",
    "3DA",
    "T5O",
    "D4M",
    "CDW",
    "2MU",
    "DGI",
    "6IA",
    "PYO",
    "6OG",
    "8AN",
    "7MG",
    "G47",
    "SRA",
    "2GT",
    "XUA",
    "4PC",
    "TED",
    "DFG",
    "4SC",
    "XCR",
    "CSF",
    "XCT",
    "5CM",
    "2EG",
    "UD5",
    "G46",
    "5FA",
    "5MU",
    "U8U",
    "T3P",
    "T4S",
    "A35",
    "SMP",
    "QUO",
    "6HT",
    "A34",
    "C25",
    "U2P",
    "P2T",
    "ATM",
    "G2S",
    "PSU",
    "XUG",
    "C38",
    "2DA",
    "ATL",
    "PST",
    "CMR",
    "DZM",
    "C32",
    "C31",
    "MG1",
    "NMS",
    "1SC",
    "6MA",
    "SDG",
    "AFG",
    "ME6",
    "S6G",
    "NMT",
    "A38",
    "EIT",
    "TCP",
    "XTR",
    "A39",
    "P5P",
    "IGU",
    "12A",
    "P",
    "125",
    "PGP",
    "DDN",
    "TAF",
    "C34",
    "T2S",
    "GAO",
    "CSL",
    "DDG",
    "5IU",
    "LCA",
    "5SE",
    "TC1",
    "M2G",
    "MCY",
    "ONE",
    "XTH",
    "TP1",
    "3TD",
    "RUS",
    "H2U",
    "TGP",
    "MTR",
    "3MU",
    "5PC",
    "YG",
    "LCG",
    "MTU",
    "C45",
    "C49",
    "TFO",
    "RSQ",
    "B7C",
    "6MZ",
    "DRM",
    "ZBC",
    "IU",
    "E1X",
    "U34",
    "U36",
    "S4U",
    "T31",
    "PR5",
    "GDR",
    "C42",
    "M5M",
    "Z",
    "JDT",
    "4OC",
    "G31",
    "U25",
    "US3",
    "XGL",
    "SSU",
    "G36",
    "YYG",
    "C43",
    "US1",
    "UMS",
    "63G",
    "U37",
    "ZDU",
    "AF2",
    "C4S",
    "3ME",
    "GMU",
    "0AP",
    "PG7",
    "T36",
    "T32",
    "T37",
    "LG",
    "EXC",
    "8FG",
    "URX",
    "YCO",
    "BGM",
    "UPS",
    "0AU",
    "5IC",
    "TFT",
    "0SP",
    "DCG",
    "IC",
    "PU",
    "2MG",
    "GF2",
    "XGR",
    "UBR",
    "SUR",
    "5BU",
    "1MG",
    "1AP",
    "0AD",
    "FNU",
    "64T",
    "TDY",
    "UMX",
    "5MC",
    "A5O",
    "2MA",
    "KAG",
    "A44",
    "CBV",
    "O2G",
    "A43",
    "5NC",
    "CCC",
    "NDU",
    "23G",
    "GX1",
    "A6G",
    "T49",
    "CNU",
    "T48",
    "CP1",
    "XCL",
    "XAL",
    "SPT",
    "CFL",
    "N5M",
    "5AA",
    "C2L",
    "N6G",
    "GCK",
    "AVC",
    "I5C",
    "2OM",
    "MA7",
    "A6A",
    "MA6",
    "OIP",
    "LHU",
    "CBR",
    "USM",
    "5PY",
    "G2L",
    "DGP",
    "DOC",
    "CB2",
    "TTD",
    "OMG",
    "SMT",
    "OGX",
    "HEU",
    "AET",
    "2OT",
    "2NT",
    "4PE",
    "FHU",
    "5FC",
    "ABR",
    "MAD",
    "4PD",
    "ABS",
    "M1G",
    "CFZ",
    "6HG",
    "0AV",
    "P2U",
    "T38",
    "5AT",
    "A23",
    "DFC",
    "HDP",
    "XTS",
    "FDG",
    "G42",
    "8AG",
    "XAD",
    "TCY",
    "PVX",
    "PRN",
    "CH",
    "5HT",
    "BOE",
    "MIA",
    "5HU",
    "PMT",
    "5FU",
    "TTI",
    "C36",
    "8OG",
    "6MC",
    "2ST",
    "2AT",
    "2PR",
    "2AU",
    "TLC",
    "8MG",
    "PPW",
    "126",
    "127",
    "C37",
    "UVX",
    "A2L",
    "PPU",
    "7DA",
    "XTL",
    "G49",
    "U2N",
    "MNU",
    "G48",
    "A3A",
    "FMG",
    "70U",
    "U2L",
    "GH3",
    "MEP",
    "10C",
    "0AM",
    "TLN",
    "S4G",
    "PGN",
    "A2M",
    "S4A",
    "UR3",
    "S2M",
    "7GU",
    "RMP",
    "DCT",
    "G38",
    "GRB",
    "63H",
    "EDA",
    "QBT",
    "TFE",
    "ZBU",
    "2AR",
    "G25",
    "AD2",
    "CX2",
    "LC",
    "GOM",
    "TFF",
    "3AU",
    "X",
    "GMS",
    "C46",
    "TA3",
    "F3H",
    "6MT",
    "G33",
    "UAR",
    "G32",
    "U33",
    "S4C",
    "MGV",
    "M4C",
    "BRU",
    "GFL",
    "U31",
    "CG1",
    "T39",
    "T23",
    "XGU",
    "RT",
    "CTG",
    "MGQ",
    "DPB",
    "1MA",
    "UFT",
    "URD",
    "D3T",
    "MMT",
    "DHU",
    "A5L",
    "FA2",
    "A3P",
    "UFR",
]


standardNucleicAcids = ["DA", "DT", "DG", "DC", "DU", "A", "T", "G", "C", "U"]


nonStandardNucleicAcids = {
    "0AD": "DG",
    "0AM": "DA",
    "0AP": "DC",
    "0AU": "DU",
    "0AV": "DA",
    "0SP": "DA",
    "10C": "C",
    "125": "U",
    "126": "U",
    "127": "U",
    "12A": "A",
    "1AP": "DA",
    "1MA": "A",
    "1MG": "G",
    "1SC": "C",
    "23G": "G",
    "2AR": "DA",
    "2AT": "DT",
    "2AU": "U",
    "2BD": "DI",
    "2BT": "DT",
    "2BU": "DA",
    "2DA": "DA",
    "2DT": "DT",
    "2EG": "G",
    "2GT": "DT",
    "2MA": "A",
    "2MG": "G",
    "2MU": "U",
    "2NT": "DT",
    "2OM": "U",
    "2OT": "DT",
    "2PR": "DG",
    "2ST": "DT",
    "3AU": "U",
    "3DA": "DA",
    "3ME": "U",
    "3MU": "U",
    "3TD": "U",
    "5CM": "DC",
    "47C": "DC",
    "4OC": "C",
    "4PC": "DC",
    "4PD": "DC",
    "4PE": "DC",
    "4SC": "DC",
    "4SU": "U",
    "5AA": "DA",
    "5AT": "DT",
    "5BU": "U",
    "5CG": "DG",
    "5FA": "A",
    "5FC": "DC",
    "5FU": "U",
    "5HT": "DT",
    "5HU": "DU",
    "5IC": "C",
    "5IU": "DU",
    "5MC": "C",
    "5MU": "U",
    "5NC": "DC",
    "5PC": "DC",
    "5PY": "DT",
    "5SE": "DU",
    "64T": "DT",
    "63G": "DG",
    "63H": "DG",
    "6HA": "DA",
    "6HC": "DC",
    "6HG": "DG",
    "6HT": "DT",
    "6IA": "A",
    "6MA": "A",
    "6MC": "A",
    "6MT": "A",
    "6MZ": "A",
    "6OG": "DG",
    "70U": "U",
    "7DA": "DA",
    "7GU": "DG",
    "7MG": "G",
    "8AG": "DG",
    "8AN": "A",
    "8FG": "DG",
    "8MG": "DG",
    "8OG": "DG",
    "A23": "A",
    "A2L": "A",
    "A2M": "A",
    "A34": "DA",
    "A35": "DA",
    "A38": "DA",
    "A39": "A",
    "A3A": "DA",
    "A3P": "A",
    "A40": "DA",
    "A43": "DA",
    "A44": "A",
    "A47": "DA",
    "A5L": "DA",
    "A5O": "A",
    "A6A": "A",
    "A6C": "C",
    "A6G": "G",
    "A6U": "U",
    "ABR": "DA",
    "ABS": "DA",
    "AD2": "DA",
    "AET": "A",
    "AF2": "DA",
    "AFG": "DG",
    "AP7": "A",
    "ATL": "DT",
    "ATM": "DT",
    "AVC": "A",
    "B7C": "DC",
    "BGM": "DG",
    "BOE": "DT",
    "BRU": "DU",
    "BVP": "DU",
    "C25": "C",
    "C2L": "C",
    "C2S": "DC",
    "C31": "C",
    "C32": "DC",
    "C34": "DC",
    "C36": "DC",
    "C37": "DC",
    "C38": "DC",
    "C42": "DC",
    "C43": "C",
    "C45": "DC",
    "C46": "DC",
    "C49": "DC",
    "C4S": "DC",
    "CB2": "DC",
    "CBR": "DC",
    "CBV": "C",
    "CCC": "C",
    "CDW": "DC",
    "CFL": "DC",
    "CFZ": "DC",
    "CG1": "G",
    "CH": "C",
    "CMR": "DC",
    "CNU": "U",
    "CP1": "DC",
    "CSF": "C",
    "CSL": "DC",
    "CTG": "DT",
    "CX2": "DC",
    "D3T": "DT",
    "D4M": "DT",
    "DCG": "DG",
    "DCT": "DC",
    "DDG": "DG",
    "DDN": "DU",
    "DFC": "DC",
    "DFG": "DG",
    "DGI": "DG",
    "DGP": "DG",
    "DHU": "U",
    "DNR": "DC",
    "DOC": "DC",
    "DPB": "DT",
    "DRM": "DU",
    "DRT": "DT",
    "DZM": "DA",
    "E1X": "DA",
    "EDA": "DA",
    "EIT": "DT",
    "EXC": "DC",
    "F3H": "DT",
    "FA2": "DA",
    "FDG": "DG",
    "FHU": "U",
    "FMG": "DG",
    "FNU": "U",
    "FOX": "DG",
    "G25": "G",
    "G2L": "G",
    "G2S": "DG",
    "G31": "DG",
    "G32": "DG",
    "G33": "DG",
    "G36": "DG",
    "G38": "DG",
    "G42": "DG",
    "G46": "G",
    "G47": "DG",
    "G48": "G",
    "G49": "DG",
    "G7M": "G",
    "GAO": "G",
    "GCK": "DC",
    "GDR": "DG",
    "GF2": "DG",
    "GFL": "DG",
    "GH3": "G",
    "GMS": "DG",
    "GMU": "DU",
    "GOM": "G",
    "GRB": "G",
    "GX1": "DG",
    "H2U": "U",
    "HDP": "DU",
    "HEU": "DU",
    "I5C": "DC",
    "IC": "C",
    "IG": "G",
    "IGU": "DG",
    "IMC": "DC",
    "IU": "U",
    "JDT": "DT",
    "KAG": "G",
    "LC": "C",
    "LCA": "A",
    "LCG": "DG",
    "LG": "G",
    "LGP": "DG",
    "LHU": "U",
    "M1G": "DG",
    "M2G": "G",
    "M4C": "C",
    "M5M": "C",
    "MA6": "A",
    "MA7": "DA",
    "MAD": "A",
    "MCY": "DC",
    "ME6": "DC",
    "MEP": "U",
    "MG1": "DG",
    "MGQ": "A",
    "MGV": "G",
    "MIA": "A",
    "MMT": "DT",
    "MNU": "U",
    "MRG": "DG",
    "MTR": "DT",
    "MTU": "A",
    "YG": "G",
    "N5M": "C",
    "N6G": "G",
    "NDN": "DU",
    "NDU": "DU",
    "NMS": "DT",
    "NMT": "DT",
    "O2G": "G",
    "OGX": "DG",
    "OHU": "DU",
    "OIP": "DI",
    "OMC": "C",
    "OMG": "G",
    "OMU": "U",
    "ONE": "U",
    "P": "DG",
    "P2T": "DT",
    "P2U": "DU",
    "P5P": "A",
    "PDU": "DU",
    "PG7": "DG",
    "PGN": "DG",
    "PGP": "G",
    "PMT": "C",
    "PPU": "A",
    "PPW": "DG",
    "PR5": "A",
    "PRN": "DA",
    "PST": "DT",
    "PSU": "U",
    "PU": "A",
    "PVX": "DC",
    "PYO": "U",
    "QBT": "T",
    "QUO": "G",
    "RIA": "A",
    "RMP": "DA",
    "RSQ": "U",
    "RT": "T",
    "RUS": "U",
    "S2M": "DT",
    "S4A": "DA",
    "S4C": "C",
    "S4G": "DG",
    "S4U": "U",
    "S6G": "DG",
    "SDG": "DG",
    "SMP": "DA",
    "SMT": "T",
    "SPT": "DT",
    "SRA": "A",
    "SSU": "U",
    "SUR": "U",
    "T23": "T",
    "T2S": "T",
    "T31": "U",
    "T32": "DT",
    "T36": "DT",
    "T37": "DT",
    "T38": "T",
    "T39": "T",
    "T3P": "DT",
    "T41": "T",
    "T48": "DT",
    "T49": "DT",
    "T4S": "DT",
    "T5O": "DU",
    "T5S": "DT",
    "T6A": "A",
    "TA3": "DT",
    "TAF": "DT",
    "TC1": "DC",
    "TCP": "DT",
    "TCY": "DA",
    "TDY": "DT",
    "TED": "DT",
    "TFE": "DT",
    "TFF": "DT",
    "TFO": "DA",
    "TFT": "DT",
    "TGP": "DG",
    "TLC": "DT",
    "TLN": "DU",
    "TP1": "DT",
    "TPC": "DC",
    "TPG": "G",
    "TTD": "DT",
    "TTI": "DU",
    "TTM": "DT",
    "U25": "U",
    "U2L": "U",
    "U2N": "DU",
    "U2P": "U",
    "U31": "U",
    "U33": "DU",
    "U34": "U",
    "U36": "U",
    "U37": "U",
    "U8U": "U",
    "UAR": "U",
    "UBR": "DU",
    "UCL": "DU",
    "UD5": "U",
    "UFR": "DU",
    "UFT": "DU",
    "UMP": "U",
    "UMS": "DU",
    "UMX": "DU",
    "UPS": "DU",
    "UR3": "U",
    "URD": "U",
    "URX": "DU",
    "US1": "DU",
    "US2": "DU",
    "US3": "DT",
    "US5": "U",
    "USM": "DU",
    "UVX": "DU",
    "X": "DG",
    "XAD": "DA",
    "XAL": "DA",
    "XCL": "DC",
    "XCR": "DC",
    "XCT": "DC",
    "XCY": "DC",
    "XGL": "DG",
    "XGR": "DG",
    "XGU": "DG",
    "XTH": "DT",
    "XTL": "DT",
    "XTR": "DT",
    "XTS": "G",
    "XUA": "DA",
    "XUG": "DG",
    "YCO": "DC",
    "YYG": "G",
    "Z": "DC",
    "ZBC": "C",
    "ZBU": "U",
    "ZDU": "DU",
}


A_G = [
    "DZM",
    "TPG",
    "GF2",
    "MG1",
    "XGR",
    "DA",
    "G46",
    "XAL",
    "7GU",
    "A39",
    "8OG",
    "6MA",
    "1MG",
    "1AP",
    "0AD",
    "SDG",
    "6MC",
    "AFG",
    "S6G",
    "2PR",
    "LGP",
    "A38",
    "8MG",
    "GRB",
    "IG",
    "A5O",
    "P5P",
    "2MA",
    "PPW",
    "A44",
    "12A",
    "2BU",
    "O2G",
    "A47",
    "A2L",
    "PGP",
    "A43",
    "A2M",
    "T6A",
    "GAO",
    "23G",
    "G49",
    "GX1",
    "DDG",
    "A6G",
    "G48",
    "M2G",
    "P",
    "A3A",
    "FMG",
    "AP7",
    "G33",
    "GFL",
    "GH3",
    "QUO",
    "5AA",
    "PPU",
    "G42",
    "DG",
    "TGP",
    "TCY",
    "A40",
    "N6G",
    "0AM",
    "AVC",
    "6OG",
    "MA7",
    "A6A",
    "PGN",
    "MTU",
    "7DA",
    "MA6",
    "G7M",
    "S4A",
    "XGL",
    "LCA",
    "G2L",
    "DGP",
    "6MZ",
    "RMP",
    "6HA",
    "G38",
    "5CG",
    "OMG",
    "FOX",
    "63H",
    "EDA",
    "3DA",
    "MAD",
    "E1X",
    "2AR",
    "G25",
    "AD2",
    "GOM",
    "OGX",
    "DGI",
    "AET",
    "6IA",
    "X",
    "GMS",
    "GDR",
    "S4G",
    "8AN",
    "7MG",
    "G47",
    "ABR",
    "LCG",
    "G31",
    "ABS",
    "M1G",
    "KAG",
    "6MT",
    "6HG",
    "XUA",
    "G36",
    "YYG",
    "AF2",
    "G32",
    "63G",
    "MRG",
    "DFG",
    "MGV",
    "A5L",
    "A23",
    "0AV",
    "A",
    "CG1",
    "XTS",
    "XGU",
    "2EG",
    "FDG",
    "5FA",
    "MGQ",
    "PG7",
    "PR5",
    "G",
    "RIA",
    "LG",
    "8AG",
    "XAD",
    "A35",
    "1MA",
    "SMP",
    "8FG",
    "A34",
    "SRA",
    "PRN",
    "BGM",
    "G2S",
    "MIA",
    "0SP",
    "DCG",
    "FA2",
    "PU",
    "IGU",
    "2MG",
    "XUG",
    "YG",
    "2DA",
    "A3P",
    "TFO",
]


C_U_T = [
    "C2S",
    "GMU",
    "CMR",
    "Z",
    "C32",
    "C31",
    "DRT",
    "T49",
    "TFF",
    "C36",
    "TTI",
    "TFT",
    "2BT",
    "US2",
    "UBR",
    "NMS",
    "1SC",
    "M5M",
    "OMC",
    "UCL",
    "TC1",
    "FNU",
    "2ST",
    "ME6",
    "2AT",
    "2AU",
    "NMT",
    "64T",
    "TDY",
    "EIT",
    "XTH",
    "UMP",
    "5MC",
    "TLC",
    "TCP",
    "TPC",
    "US1",
    "XTR",
    "F3H",
    "US5",
    "126",
    "T",
    "CBV",
    "127",
    "C37",
    "DC",
    "DNR",
    "UVX",
    "4SU",
    "125",
    "DDN",
    "CFL",
    "C34",
    "U",
    "5NC",
    "CCC",
    "T39",
    "NDU",
    "XTL",
    "47C",
    "NDN",
    "U2N",
    "5IU",
    "5SE",
    "CNU",
    "A6C",
    "2DT",
    "XCL",
    "XCY",
    "MCY",
    "OHU",
    "70U",
    "SUR",
    "5BU",
    "U2L",
    "ONE",
    "DU",
    "TP1",
    "SPT",
    "XCT",
    "PDU",
    "DT",
    "3TD",
    "N5M",
    "TTM",
    "MEP",
    "RUS",
    "H2U",
    "C2L",
    "MTR",
    "3MU",
    "A6U",
    "GCK",
    "I5C",
    "2OM",
    "PVX",
    "UPS",
    "C45",
    "UR3",
    "LHU",
    "IMC",
    "CBR",
    "T2S",
    "T5O",
    "5PY",
    "UFT",
    "RSQ",
    "B7C",
    "DCT",
    "DOC",
    "DRM",
    "CSL",
    "UAR",
    "T5S",
    "CB2",
    "T41",
    "QBT",
    "BVP",
    "6HC",
    "TFE",
    "IU",
    "TTD",
    "C",
    "C49",
    "S2M",
    "ZBU",
    "ZBC",
    "CDW",
    "CX2",
    "LC",
    "U36",
    "2MU",
    "S4U",
    "TLN",
    "SMT",
    "HEU",
    "3AU",
    "T31",
    "M4C",
    "PYO",
    "U34",
    "ATM",
    "C42",
    "2OT",
    "2NT",
    "4PE",
    "FHU",
    "5FC",
    "JDT",
    "4PD",
    "C46",
    "4OC",
    "U25",
    "US3",
    "TA3",
    "CFZ",
    "2GT",
    "4PC",
    "OMU",
    "TAF",
    "C43",
    "TED",
    "UMS",
    "U33",
    "MNU",
    "U37",
    "S4C",
    "D4M",
    "P2U",
    "U31",
    "5AT",
    "BRU",
    "4SC",
    "DFC",
    "C4S",
    "T38",
    "UMX",
    "T48",
    "HDP",
    "T23",
    "CSF",
    "RT",
    "3ME",
    "CP1",
    "5CM",
    "10C",
    "UD5",
    "XCR",
    "0AP",
    "T36",
    "SSU",
    "DPB",
    "5MU",
    "U8U",
    "T37",
    "T3P",
    "T4S",
    "EXC",
    "6HT",
    "URX",
    "5PC",
    "YCO",
    "C25",
    "U2P",
    "USM",
    "URD",
    "D3T",
    "P2T",
    "UFR",
    "CH",
    "5HT",
    "0AU",
    "PSU",
    "5IC",
    "BOE",
    "5HU",
    "DHU",
    "T32",
    "IC",
    "CTG",
    "MMT",
    "C38",
    "PMT",
    "ATL",
    "5FU",
    "PST",
]


# Conversion of three-letter aminoacid code into one-letter code
aminoacidCode = {
    "GLY": "G",
    "PRO": "P",
    "ALA": "A",
    "VAL": "V",
    "LEU": "L",
    "ILE": "I",
    "MET": "M",
    "CYS": "C",
    "PHE": "F",
    "TYR": "Y",
    "TRP": "W",
    "HIS": "H",
    "LYS": "K",
    "ARG": "R",
    "GLN": "Q",
    "ASN": "N",
    "GLU": "E",
    "SER": "S",
    "THR": "T",
    "ASP": "D",
    "SEC": "U",
    "PYL": "O",
}


metalList = [
    "LI",
    "BE",
    "NA",
    "MG",
    "AL",
    "K",
    "CA",
    "SC",
    "TI",
    "V",
    "CR",
    "MN",
    "FE",
    "CO",
    "NI",
    "CU",
    "ZN",
    "GA",
    "GE",
    "RB",
    "SR",
    "Y",
    "ZR",
    "NB",
    "MO",
    "TC",
    "RU",
    "RH",
    "PD",
    "AG",
    "CD",
    "IN",
    "SN",
    "SB",
    "CS",
    "BA",
    "LA",
    "CE",
    "PR",
    "ND",
    "PM",
    "SM",
    "EU",
    "GD",
    "TB",
    "DY",
    "HO",
    "ER",
    "TM",
    "YB",
    "LU",
    "HF",
    "TA",
    "W",
    "RE",
    "OS",
    "IR",
    "PT",
    "AU",
    "HG",
    "TL",
    "PB",
    "BI",
    "PO",
    "FR",
    "RA",
    "AC",
    "TH",
    "PA",
    "NP",
    "PU",
    "AM",
    "CM",
    "BK",
    "CF",
    "ES",
    "FM",
    "MD",
    "NO",
    "LR",
    "RF",
    "DB",
    "SG",
    "AS",
]
# U removed for conflicts with uracile

metals_chemicalElem_and_atomicNum = {
    "LI": 3,
    "BE": 4,
    "NA": 11,
    "MG": 12,
    "AL": 13,
    "K": 19,
    "CA": 20,
    "SC": 21,
    "TI": 22,
    "V": 23,
    "CR": 24,
    "MN": 25,
    "FE": 26,
    "CO": 27,
    "NI": 28,
    "CU": 29,
    "ZN": 30,
    "GA": 31,
    "GE": 32,
    "RB": 37,
    "SR": 38,
    "Y": 39,
    "ZR": 40,
    "NB": 41,
    "MO": 42,
    "TC": 43,
    "RU": 44,
    "RH": 45,
    "PD": 46,
    "AG": 47,
    "CD": 48,
    "IN": 49,
    "SN": 50,
    "SB": 51,
    "CS": 55,
    "BA": 56,
    "LA": 57,
    "CE": 58,
    "PR": 59,
    "ND": 60,
    "PM": 61,
    "SM": 62,
    "EU": 63,
    "GD": 64,
    "TB": 65,
    "DY": 66,
    "HO": 67,
    "ER": 68,
    "TM": 69,
    "YB": 70,
    "LU": 71,
    "HF": 72,
    "TA": 73,
    "W": 74,
    "RE": 75,
    "OS": 76,
    "IR": 77,
    "PT": 78,
    "AU": 79,
    "HG": 80,
    "TL": 81,
    "PB": 82,
    "BI": 83,
    "PO": 84,
    "FR": 87,
    "RA": 88,
    "AC": 89,
    "TH": 90,
    "PA": 91,
    "U": 92,
    "NP": 93,
    "PU": 94,
    "AM": 95,
    "CM": 96,
    "BK": 97,
    "CF": 98,
    "ES": 99,
    "FM": 100,
    "MD": 101,
    "NO": 102,
    "LR": 103,
    "RF": 104,
    "DB": 105,
    "SG": 106,
    "AS": 33,
}


scoringMatrixBlosum62 = {
    "ALA": {
        "ALA": 4,
        "ARG": -1,
        "ASN": -2,
        "ASP": -2,
        "CYS": 0,
        "GLN": -1,
        "GLU": -1,
        "GLY": 0,
        "HIS": -2,
        "ILE": -1,
        "LEU": -1,
        "LYS": -1,
        "MET": -1,
        "PHE": -2,
        "PRO": -1,
        "SER": 1,
        "THR": 0,
        "TRP": -3,
        "TYR": -2,
        "VAL": 0,
        "ASX": -2,
        "GLX": -1,
        "XAA": 0,
    },
    "ARG": {
        "ALA": -1,
        "ARG": 5,
        "ASN": 0,
        "ASP": -2,
        "CYS": -3,
        "GLN": 1,
        "GLU": 0,
        "GLY": -2,
        "HIS": 0,
        "ILE": -3,
        "LEU": -2,
        "LYS": 2,
        "MET": -1,
        "PHE": -3,
        "PRO": -2,
        "SER": -1,
        "THR": -1,
        "TRP": -3,
        "TYR": -2,
        "VAL": -3,
        "ASX": -1,
        "GLX": 0,
        "XAA": -1,
    },
    "ASN": {
        "ALA": -2,
        "ARG": 0,
        "ASN": 6,
        "ASP": 1,
        "CYS": -3,
        "GLN": 0,
        "GLU": 0,
        "GLY": 0,
        "HIS": 1,
        "ILE": -3,
        "LEU": -3,
        "LYS": 0,
        "MET": -2,
        "PHE": -3,
        "PRO": -2,
        "SER": 1,
        "THR": 0,
        "TRP": -4,
        "TYR": -2,
        "VAL": -3,
        "ASX": 3,
        "GLX": 0,
        "XAA": -1,
    },
    "ASP": {
        "ALA": -2,
        "ARG": -2,
        "ASN": 1,
        "ASP": 6,
        "CYS": -3,
        "GLN": 0,
        "GLU": 2,
        "GLY": -1,
        "HIS": -1,
        "ILE": -3,
        "LEU": -4,
        "LYS": -1,
        "MET": -3,
        "PHE": -3,
        "PRO": -1,
        "SER": 0,
        "THR": -1,
        "TRP": -4,
        "TYR": -3,
        "VAL": -3,
        "ASX": 4,
        "GLX": 1,
        "XAA": -1,
    },
    "CYS": {
        "ALA": 0,
        "ARG": -3,
        "ASN": -3,
        "ASP": -3,
        "CYS": 9,
        "GLN": -3,
        "GLU": -4,
        "GLY": -3,
        "HIS": -3,
        "ILE": -1,
        "LEU": -1,
        "LYS": -3,
        "MET": -1,
        "PHE": -2,
        "PRO": -3,
        "SER": -1,
        "THR": -1,
        "TRP": -2,
        "TYR": -2,
        "VAL": -1,
        "ASX": -3,
        "GLX": -3,
        "XAA": -2,
    },
    "GLN": {
        "ALA": -1,
        "ARG": 1,
        "ASN": 0,
        "ASP": 0,
        "CYS": -3,
        "GLN": 5,
        "GLU": 2,
        "GLY": -2,
        "HIS": 0,
        "ILE": -3,
        "LEU": -2,
        "LYS": 1,
        "MET": 0,
        "PHE": -3,
        "PRO": -1,
        "SER": 0,
        "THR": -1,
        "TRP": -2,
        "TYR": -1,
        "VAL": -2,
        "ASX": 0,
        "GLX": 3,
        "XAA": -1,
    },
    "GLU": {
        "ALA": -1,
        "ARG": 0,
        "ASN": 0,
        "ASP": 2,
        "CYS": -4,
        "GLN": 2,
        "GLU": 5,
        "GLY": -2,
        "HIS": 0,
        "ILE": -3,
        "LEU": -3,
        "LYS": 1,
        "MET": -2,
        "PHE": -3,
        "PRO": -1,
        "SER": 0,
        "THR": -1,
        "TRP": -3,
        "TYR": -2,
        "VAL": -2,
        "ASX": 1,
        "GLX": 4,
        "XAA": -1,
    },
    "GLY": {
        "ALA": 0,
        "ARG": -2,
        "ASN": 0,
        "ASP": -1,
        "CYS": -3,
        "GLN": -2,
        "GLU": -2,
        "GLY": 6,
        "HIS": -2,
        "ILE": -4,
        "LEU": -4,
        "LYS": -2,
        "MET": -3,
        "PHE": -3,
        "PRO": -2,
        "SER": 0,
        "THR": -2,
        "TRP": -2,
        "TYR": -3,
        "VAL": -3,
        "ASX": -1,
        "GLX": -2,
        "XAA": -1,
    },
    "HIS": {
        "ALA": -2,
        "ARG": 0,
        "ASN": 1,
        "ASP": -1,
        "CYS": -3,
        "GLN": 0,
        "GLU": 0,
        "GLY": -2,
        "HIS": 8,
        "ILE": -3,
        "LEU": -3,
        "LYS": -1,
        "MET": -2,
        "PHE": -1,
        "PRO": -2,
        "SER": -1,
        "THR": -2,
        "TRP": -2,
        "TYR": 2,
        "VAL": -3,
        "ASX": 0,
        "GLX": 0,
        "XAA": -1,
    },
    "ILE": {
        "ALA": -1,
        "ARG": -3,
        "ASN": -3,
        "ASP": -3,
        "CYS": -1,
        "GLN": -3,
        "GLU": -3,
        "GLY": -4,
        "HIS": -3,
        "ILE": 4,
        "LEU": 2,
        "LYS": -3,
        "MET": 1,
        "PHE": 0,
        "PRO": -3,
        "SER": -2,
        "THR": -1,
        "TRP": -3,
        "TYR": -1,
        "VAL": 3,
        "ASX": -3,
        "GLX": -3,
        "XAA": -1,
    },
    "LEU": {
        "ALA": -1,
        "ARG": -2,
        "ASN": -3,
        "ASP": -4,
        "CYS": -1,
        "GLN": -2,
        "GLU": -3,
        "GLY": -4,
        "HIS": -3,
        "ILE": 2,
        "LEU": 4,
        "LYS": -2,
        "MET": 2,
        "PHE": 0,
        "PRO": -3,
        "SER": -2,
        "THR": -1,
        "TRP": -2,
        "TYR": -1,
        "VAL": 1,
        "ASX": -4,
        "GLX": -3,
        "XAA": -1,
    },
    "LYS": {
        "ALA": -1,
        "ARG": 2,
        "ASN": 0,
        "ASP": -1,
        "CYS": -3,
        "GLN": 1,
        "GLU": 1,
        "GLY": -2,
        "HIS": -1,
        "ILE": -3,
        "LEU": -2,
        "LYS": 5,
        "MET": -1,
        "PHE": -3,
        "PRO": -1,
        "SER": 0,
        "THR": -1,
        "TRP": -3,
        "TYR": -2,
        "VAL": -2,
        "ASX": 0,
        "GLX": 1,
        "XAA": -1,
    },
    "MET": {
        "ALA": -1,
        "ARG": -1,
        "ASN": -2,
        "ASP": -3,
        "CYS": -1,
        "GLN": 0,
        "GLU": -2,
        "GLY": -3,
        "HIS": -2,
        "ILE": 1,
        "LEU": 2,
        "LYS": -1,
        "MET": 5,
        "PHE": 0,
        "PRO": -2,
        "SER": -1,
        "THR": -1,
        "TRP": -1,
        "TYR": -1,
        "VAL": 1,
        "ASX": -3,
        "GLX": -1,
        "XAA": -1,
    },
    "PHE": {
        "ALA": -2,
        "ARG": -3,
        "ASN": -3,
        "ASP": -3,
        "CYS": -2,
        "GLN": -3,
        "GLU": -3,
        "GLY": -3,
        "HIS": -1,
        "ILE": 0,
        "LEU": 0,
        "LYS": -3,
        "MET": 0,
        "PHE": 6,
        "PRO": -4,
        "SER": -2,
        "THR": -2,
        "TRP": 1,
        "TYR": 3,
        "VAL": -1,
        "ASX": -3,
        "GLX": -3,
        "XAA": -1,
    },
    "PRO": {
        "ALA": -1,
        "ARG": -2,
        "ASN": -2,
        "ASP": -1,
        "CYS": -3,
        "GLN": -1,
        "GLU": -1,
        "GLY": -2,
        "HIS": -2,
        "ILE": -3,
        "LEU": -3,
        "LYS": -1,
        "MET": -2,
        "PHE": -4,
        "PRO": 7,
        "SER": -1,
        "THR": -1,
        "TRP": -4,
        "TYR": -3,
        "VAL": -2,
        "ASX": -2,
        "GLX": -1,
        "XAA": -2,
    },
    "SER": {
        "ALA": 1,
        "ARG": -1,
        "ASN": 1,
        "ASP": 0,
        "CYS": -1,
        "GLN": 0,
        "GLU": 0,
        "GLY": 0,
        "HIS": -1,
        "ILE": -2,
        "LEU": -2,
        "LYS": 0,
        "MET": -1,
        "PHE": -2,
        "PRO": -1,
        "SER": 4,
        "THR": 1,
        "TRP": -3,
        "TYR": -2,
        "VAL": -2,
        "ASX": 0,
        "GLX": 0,
        "XAA": 0,
    },
    "THR": {
        "ALA": 0,
        "ARG": -1,
        "ASN": 0,
        "ASP": -1,
        "CYS": -1,
        "GLN": -1,
        "GLU": -1,
        "GLY": -2,
        "HIS": -2,
        "ILE": -1,
        "LEU": -1,
        "LYS": -1,
        "MET": -1,
        "PHE": -2,
        "PRO": -1,
        "SER": 1,
        "THR": 5,
        "TRP": -2,
        "TYR": -2,
        "VAL": 0,
        "ASX": -1,
        "GLX": -1,
        "XAA": 0,
    },
    "TRP": {
        "ALA": -3,
        "ARG": -3,
        "ASN": -4,
        "ASP": -4,
        "CYS": -2,
        "GLN": -2,
        "GLU": -3,
        "GLY": -2,
        "HIS": -2,
        "ILE": -3,
        "LEU": -2,
        "LYS": -3,
        "MET": -1,
        "PHE": 1,
        "PRO": -4,
        "SER": -3,
        "THR": -2,
        "TRP": 11,
        "TYR": 2,
        "VAL": -3,
        "ASX": -4,
        "GLX": -3,
        "XAA": -2,
    },
    "TYR": {
        "ALA": -2,
        "ARG": -2,
        "ASN": -2,
        "ASP": -3,
        "CYS": -2,
        "GLN": -1,
        "GLU": -2,
        "GLY": -3,
        "HIS": 2,
        "ILE": -1,
        "LEU": -1,
        "LYS": -2,
        "MET": -1,
        "PHE": 3,
        "PRO": -3,
        "SER": -2,
        "THR": -2,
        "TRP": 2,
        "TYR": 7,
        "VAL": -1,
        "ASX": -3,
        "GLX": -2,
        "XAA": -1,
    },
    "VAL": {
        "ALA": 0,
        "ARG": -3,
        "ASN": -3,
        "ASP": -3,
        "CYS": -1,
        "GLN": -2,
        "GLU": -2,
        "GLY": -3,
        "HIS": -3,
        "ILE": 3,
        "LEU": 1,
        "LYS": -2,
        "MET": 1,
        "PHE": -1,
        "PRO": -2,
        "SER": -2,
        "THR": 0,
        "TRP": -3,
        "TYR": -1,
        "VAL": 4,
        "ASX": -3,
        "GLX": -2,
        "XAA": -1,
    },
    "ASX": {
        "ALA": -2,
        "ARG": -1,
        "ASN": 3,
        "ASP": 4,
        "CYS": -3,
        "GLN": 0,
        "GLU": 1,
        "GLY": -1,
        "HIS": 0,
        "ILE": -3,
        "LEU": -4,
        "LYS": 0,
        "MET": -3,
        "PHE": -3,
        "PRO": -2,
        "SER": 0,
        "THR": -1,
        "TRP": -4,
        "TYR": -3,
        "VAL": -3,
        "ASX": 4,
        "GLX": 1,
        "XAA": -1,
    },
    "GLX": {
        "ALA": -1,
        "ARG": 0,
        "ASN": 0,
        "ASP": 1,
        "CYS": -3,
        "GLN": 3,
        "GLU": 4,
        "GLY": -2,
        "HIS": 0,
        "ILE": -3,
        "LEU": -3,
        "LYS": 1,
        "MET": -1,
        "PHE": -3,
        "PRO": -1,
        "SER": 0,
        "THR": -1,
        "TRP": -3,
        "TYR": -2,
        "VAL": -2,
        "ASX": 1,
        "GLX": 4,
        "XAA": -1,
    },
    "XAA": {
        "ALA": 0,
        "ARG": -1,
        "ASN": -1,
        "ASP": -1,
        "CYS": -2,
        "GLN": -1,
        "GLU": -1,
        "GLY": -1,
        "HIS": -1,
        "ILE": -1,
        "LEU": -1,
        "LYS": -1,
        "MET": -1,
        "PHE": -1,
        "PRO": -2,
        "SER": 0,
        "THR": 0,
        "TRP": -2,
        "TYR": -1,
        "VAL": -1,
        "ASX": -1,
        "GLX": -1,
        "XAA": -1,
    },
}


nucleicAcidsScoringMatrix = {
    "DA": {
        "DA": 5,
        "DT": -4,
        "DG": -4,
        "DC": -4,
        "DU": -4,
        "A": 5,
        "T": -4,
        "G": -4,
        "C": -4,
        "U": -4,
    },
    "DT": {
        "DA": -4,
        "DT": 5,
        "DG": -4,
        "DC": -4,
        "DU": 5,
        "A": -4,
        "T": 5,
        "G": -4,
        "C": -4,
        "U": 5,
    },
    "DG": {
        "DA": -4,
        "DT": -4,
        "DG": 5,
        "DC": -4,
        "DU": -4,
        "A": -4,
        "T": -4,
        "G": 5,
        "C": -4,
        "U": -4,
    },
    "DC": {
        "DA": -4,
        "DT": -4,
        "DG": -4,
        "DC": 5,
        "DU": -4,
        "A": -4,
        "T": -4,
        "G": -4,
        "C": 5,
        "U": -4,
    },
    "DU": {
        "DA": -4,
        "DT": 5,
        "DG": -4,
        "DC": -4,
        "DU": 5,
        "A": -4,
        "T": 5,
        "G": -4,
        "C": -4,
        "U": 5,
    },
    "A": {
        "A": 5,
        "T": -4,
        "G": -4,
        "C": -4,
        "U": -4,
        "DA": 5,
        "DT": -4,
        "DG": -4,
        "DC": -4,
        "DU": -4,
    },
    "T": {
        "A": -4,
        "T": 5,
        "G": -4,
        "C": -4,
        "U": 5,
        "DA": -4,
        "DT": 5,
        "DG": -4,
        "DC": -4,
        "DU": 5,
    },
    "G": {
        "A": -4,
        "T": -4,
        "G": 5,
        "C": -4,
        "U": -4,
        "DA": -4,
        "DT": -4,
        "DG": 5,
        "DC": -4,
        "DU": -4,
    },
    "C": {
        "A": -4,
        "T": -4,
        "G": -4,
        "C": 5,
        "U": -4,
        "DA": -4,
        "DT": -4,
        "DG": -4,
        "DC": 5,
        "DU": -4,
    },
    "U": {
        "A": -4,
        "T": 5,
        "G": -4,
        "C": -4,
        "U": 5,
        "DA": -4,
        "DT": 5,
        "DG": -4,
        "DC": -4,
        "DU": 5,
    },
}
